---
title: "11_correlations"
author: "Jackie"
date: "11/11/2020"
output: html_notebook
---

```{r, message=FALSE}
library(glmnet)
library(glmpath)
library(lars)
library(tidyverse)
library(dynutils)
library(readxl)
library(haven)
library(naniar)
library(pscl)
library(MASS)
library(stringr)
library(sjPlot)
library(directlabels)
library(caret)

set.seed(1234)
```


```{r, message=FALSE, echo=FALSE}
graph_net_fp <- "~/Box/Mooddata_Coordinating/1_Lab_Coordinating/Users/JackieSchwartz/PHIND_RS_and_Suicide/Octo2020Analysis/siq_graph.csv"

graph_net <- read_csv(graph_net_fp)

sleepiness_fp <- "~/Box/Mooddata_Coordinating/1_Lab_Coordinating/Users/JackieSchwartz/PHIND_RS_and_Suicide/Octo2020Analysis/sleepiness.xlsx"

sleepy <- read_excel(sleepiness_fp) %>%
  rename("sleepy" = `sleepiness (1 = yes, 0 = no)`) %>%
  dplyr::select(-`during which part of scan?`)

graph_net <- left_join(graph_net,
                       sleepy,
                       by = "ELS_ID")
```

```{r}
options(scipen=999) 
z_score <- function(x) {
diff_mu <- x - mean(x, na.rm = T)
sd <- sd(x, na.rm = T)
diff_mu / sd
}
```


# correlations
```{r}
graph_net_stand <-
  graph_net %>%
  mutate(ELS_ID = factor(ELS_ID),
         KSADS_Child_Race_by_P.T1 = factor(KSADS_Child_Race_by_P.T1),
         sex_child = factor(sex_child),
         sleepy = factor(sleepy),
         KSADS_Child_Race_by_P.T1_bin = ifelse(KSADS_Child_Race_by_P.T1 == "1", "1", "0"),
         KSADS_Child_Race_by_P.T1_bin = factor(KSADS_Child_Race_by_P.T1_bin)
  ) %>%
  dplyr::select(-KSADS_Child_Race_by_P.T1, -T1_KSADS_C_or_P_Thoughts, -T1_KSADS_C_or_P_bx, -siq_total_log) %>%
  # stnadardizing variables
  mutate_at(vars(-ELS_ID, -sex_child, -KSADS_Child_Race_by_P.T1_bin, -meds_baseline, -sleepy), z_score) 
```

# siq
```{r}
cor.test(graph_net_stand$siq_total.T3, graph_net_stand$T1_YSR_old_Internalizing_Problems_Total_Score) # 0.1812804

cor.test(graph_net_stand$siq_total.T3, graph_net_stand$caudIFG_R_34.deg) # -0.2824903

cor.test(graph_net_stand$siq_total.T3, graph_net_stand$caudvlPrG_L_63.deg) # -0.1501055

cor.test(graph_net_stand$siq_total.T3, graph_net_stand$SN_R_226.wm_z) # 0.2096495

cor.test(graph_net_stand$siq_total.T3, graph_net_stand$medventFuG_L_105.deg) # 0.2285399

cor.test(graph_net_stand$siq_total.T3, graph_net_stand$intlatITG_L_95.deg) # 0.1843783

cor.test(graph_net_stand$siq_total.T3, graph_net_stand$sgCG_R_188.eig_cent) # 0.139644

cor.test(graph_net_stand$siq_total.T3, graph_net_stand$rostdorIPL_R_138.wm_z)  # -0.06983533 
```

# ysr
```{r}
cor.test(graph_net_stand$T3_YSR_New_Internalizing_Problems_Total_Score, graph_net_stand$intlatITG_L_95.eig_cent) # 0.3218807

summary(lm(T3_YSR_New_Internalizing_Problems_Total_Score ~ sex_child, data = graph_net_stand)) # 0.5692

cor.test(graph_net_stand$T3_YSR_New_Internalizing_Problems_Total_Score, graph_net_stand$medventFuG_R_106.deg) # 0.255075

cor.test(graph_net_stand$T3_YSR_New_Internalizing_Problems_Total_Score, graph_net_stand$T1_YSR_old_Internalizing_Problems_Total_Score) # 0.2857085

cor.test(graph_net_stand$T3_YSR_New_Internalizing_Problems_Total_Score, graph_net_stand$Age_S1.T1) # -0.2665734 

cor.test(graph_net_stand$T3_YSR_New_Internalizing_Problems_Total_Score, graph_net_stand$caudIFG_R_34.deg) # -0.2800311 

cor.test(graph_net_stand$T3_YSR_New_Internalizing_Problems_Total_Score, graph_net_stand$caudPhG_L_111.eff_loc) # 0.2266781

cor.test(graph_net_stand$T3_YSR_New_Internalizing_Problems_Total_Score, graph_net_stand$vIFG_L_39.eig_cent) # -0.2496509 

cor.test(graph_net_stand$T3_YSR_New_Internalizing_Problems_Total_Score, graph_net_stand$orbOrG_R_44.pc) # -0.2276543  
```


# participant characteristic correlations
```{r}
summary(lm(siq_total.T3 ~ sex_child, data = graph_net_stand))# 0.43 (p = 0.0258)

summary(lm(siq_total.T3 ~ KSADS_Child_Race_by_P.T1_bin, data = graph_net_stand)) #-0.07 (p = 0.726)

summary(lm(siq_total.T3 ~ Age_S1.T1, data = graph_net_stand)) # -0.20 (p = 0.0396)

summary(lm(siq_total.T3 ~ Tanner_Average.T1, data = graph_net_stand)) # 0.03 (p = .743) 

summary(lm(siq_total.T3 ~ T1_YSR_old_Internalizing_Problems_Total_Score, data = graph_net_stand)) # 0.18 (p = 0.0592)

summary(lm(siq_total.T3 ~ interval_s2t1_s1t3, data = graph_net_stand)) # 0.20 (p = 0.035)

summary(lm(siq_total.T3 ~ sumsev_type_t1, data = graph_net_stand)) # 0.16 (p = 0.0937)

summary(lm(siq_total.T3 ~ sss_t1, data = graph_net_stand)) # 0.04 (p = 0.675)

summary(lm(siq_total.T3 ~ Parent_Education.T1, data = graph_net_stand)) # 0.13 (p = 0.184)

summary(lm(siq_total.T3 ~ MeanFD, data = graph_net_stand)) # 0.016 (p=0.8691)

summary(lm(siq_total.T3 ~ BMI, data = graph_net_stand)) # 0.00000211044348803693 (p=1)

summary(lm(siq_total.T3 ~ sleepy, data = graph_net_stand)) # 0.3359 (0.0987)

p <- c(0.0258, 0.726, 0.0396, .743 , 0.0592, 0.035, 0.0937,0.675, 0.184, 0.8691, 1, 0.0987)
p.adjust(p, method ="fdr", n = length(p))
# 0.1584000 0.8916000 0.1584000 0.8916000 0.1776000 0.1584000 0.1974000 0.8916000 0.3154286, 0.9481091, 1.0000000, 0.1974000

summary(lm(siq_total.T3 ~ Tanner_Average.T1*sex_child, data = graph_net_stand)) # just sex
summary(lm(siq_total.T3 ~ meds_baseline, data = graph_net_stand)) # 0.029179 (p=.913)
```

## correlations with mean fd
```{r}
summary(lm(MeanFD ~ T1_YSR_old_Internalizing_Problems_Total_Score, data = graph_net_stand)) # -0.0410864826523191228880 (p=0.671)
summary(lm(MeanFD ~ caudIFG_R_34.deg, data = graph_net_stand)) # 0.112125241372850806276 (p=0.246)
summary(lm(MeanFD ~ caudvlPrG_L_63.deg, data = graph_net_stand)) # 0.148532746729094278226 (p=0.123)
summary(lm(MeanFD ~ SN_R_226.wm_z, data = graph_net_stand)) # -0.017570896445226486665 (p=0.856)
summary(lm(MeanFD ~ medventFuG_L_105.deg, data = graph_net_stand)) # -0.026220436165970469750 (p=0.787)
summary(lm(MeanFD ~ intlatITG_L_95.deg, data = graph_net_stand)) # -0.27178368207123015932 (p=0.00425)**
summary(lm(MeanFD ~ sgCG_R_188.eig_cent, data = graph_net_stand)) # -0.077012712801159635689 (p=0.426)
summary(lm(MeanFD ~ rostdorIPL_R_140.wm_z, data = graph_net_stand)) # -0.0177039951528672016845 (p=0.855)
p <- c(0.671, p=0.246, 0.123, 0.856 , 0.787, 0.00425, 0.426, 0.855)
p.adjust(p, method ="fdr", n = length(p))
# 0.856 0.656 0.492 0.856 0.856 0.034 0.852 0.856
```

Does degree of the L inlatITG correlate with SI above and beyond mean FD?
```{r}
summary(lm(siq_total.T3 ~ intlatITG_L_95.deg + MeanFD, data = graph_net_stand))
```
yes - intlatITG is associated with severity of SI above and beyond MeanFD.
